language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

branches:
    except:
        - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.3
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
          dist: trusty
        - php: 5.4
          dist: trusty
        - php: 5.3
          dist: precise

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress
